#pragma once

enum INPUT_EVENT 
{
    NO_EVENT,
    CAMERA_TURN_LEFT,
    CAMERA_TURN_RIGHT,
    CAMERA_TURN_UP,
    CAMERA_TURN_DOWN,
    CAMERA_MOVE_LEFT,
    CAMERA_MOVE_RIGHT,
    CAMERA_MOVE_UP,
    CAMERA_MOVE_DOWN,
    CAMERA_RESET,
    CAMERA_FORWARD_BACKWARD,
    APPLICATION_EXIT,
    WIREFRAME_MODE,
    INPUT_EVENT_MAX
};